server:
  port: 9000
spring:
  kafka:
    consumer:
      bootstrap-servers: 172.16.3.230:9092,172.16.3.187:9092,172.16.3.215:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.16.3.230:9092,172.16.3.187:9092,172.16.3.215:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='admin' password='XXXXXXXXXX';
